# Generated by Django 4.1 on 2022-08-09 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('doctors', '0002_alter_doctor_detail_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_detail',
            name='medical_speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.speciality'),
        ),
    ]
